In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

# Ruta al archivo CSV en Google Drive
file_path = '/content/drive/MyDrive/AUTONOMA/TESIS/2024/Base de datos/bd_2.csv'

# Leer el archivo CSV en un DataFrame
df = pd.read_csv(file_path)

# Mostrar las primeras filas del DataFrame
print(df.head(5))

   id_estudiante                                      notas_detalle
0              1  [{"año" : "6", "periodo" : "Periodo 1", "mater...
1              2  [{"año" : "6", "periodo" : "Periodo 1", "mater...
2              3  [{"año" : "6", "periodo" : "Periodo 1", "mater...
3              4  [{"año" : "6", "periodo" : "Periodo 1", "mater...
4              5  [{"año" : "6", "periodo" : "Periodo 1", "mater...


In [ ]:
import json
# Inicializar una lista vacía para almacenar los dataframes temporales
dfs_temporales = []

for indice, fila in df.iterrows():
    # Transformar la cadena JSON en un diccionario y luego en un DataFrame
    notas_df = pd.DataFrame(json.loads(fila['notas_detalle']))

    # Añadir la columna 'id_estudiante' con el valor correspondiente
    notas_df['id_estudiante'] = fila['id_estudiante']

    # Añadir este DataFrame temporal a la lista
    dfs_temporales.append(notas_df)

# Concatenar todos los DataFrames temporales en uno solo
df_expandido = pd.concat(dfs_temporales, ignore_index=True)


In [ ]:
#eliminar todas las filas que tenga en periodo "Nota Final"

df_expandido = df_expandido[df_expandido.periodo != 'Nota Final']


In [ ]:
df_expandido

año    periodo      materia  nota  id_estudiante
0       6  Periodo 1  Matemáticas  4.60              1
1       6  Periodo 1      Español  3.29              1
2       6  Periodo 1     Biología  4.53              1
3       6  Periodo 1  C. Sociales  2.32              1
4       6  Periodo 1       Inglés  4.33              1
...    ..        ...          ...   ...            ...
10489  11  Periodo 3  Informática  2.35             40
10490  11  Periodo 3        Artes  1.18             40
10491  11  Periodo 3     Religión  4.63             40
10492  11  Periodo 3    Filosofía  3.00             40
10493  11  Periodo 3     Economía  1.27             40

[7920 rows x 5 columns]

In [ ]:
materias_dict_invertido = {
    "Matemáticas": 1,
    "Español": 2,
    "Biología": 3,
    "C. Sociales": 4,
    "Inglés": 5,
    "Edu. Física": 6,
    "Informática": 7,
    "Artes": 8,
    "Religión": 9,
    "Filosofía": 10,
    "Economía": 11
}

df_expandido['materia'] = df_expandido['materia'].replace(materias_dict_invertido)

In [ ]:
df_expandido.shape

(7920, 5)

In [ ]:
# prompt: quiero mas datos de el datafrime df_expandido

# Número de filas y columnas del DataFrame
print(f"Número de filas: {df_expandido.shape[0]}")
print(f"Número de columnas: {df_expandido.shape[1]}")

# Nombres de las columnas
print(f"Nombres de las columnas: {list(df_expandido.columns)}")

# Tipos de datos de cada columna
print(f"Tipos de datos de las columnas: {df_expandido.dtypes}")

# Resumen estadístico del DataFrame
print(df_expandido.describe())


Número de filas: 7920
Número de columnas: 5
Nombres de las columnas: ['año', 'periodo', 'materia', 'nota', 'id_estudiante']
Tipos de datos de las columnas: año               object
periodo           object
materia            int64
nota             float64
id_estudiante      int64
dtype: object
           materia         nota  id_estudiante
count  7920.000000  7920.000000    7920.000000
mean      6.000000     3.010888      20.500000
std       3.162477     1.157041      11.544125
min       1.000000     1.000000       1.000000
25%       3.000000     2.030000      10.750000
50%       6.000000     3.020000      20.500000
75%       9.000000     4.012500      30.250000
max      11.000000     5.000000      40.000000


In [ ]:
# prompt: # prompt: dividir cada el dataframe con todos los que tengan id_estudiante = 1  df_estudiante_1 = df_expandido[df_expandido['id_estudiante'] == 1] como hago esto para cada id_estudiantes y obtener una lista de dataframes

estudiantes_unicos = df_expandido['id_estudiante'].unique()
dataframes_por_estudiante = []
for estudiante in estudiantes_unicos:
  df_estudiante = df_expandido[df_expandido['id_estudiante'] == estudiante]
  dataframes_por_estudiante.append(df_estudiante)


In [ ]:
#lista de dataframe por estudiante con su codigo id
dataframes_por_estudiante[0]

año    periodo  materia  nota  id_estudiante
0     6  Periodo 1        1  4.60              1
1     6  Periodo 1        2  3.29              1
2     6  Periodo 1        3  4.53              1
3     6  Periodo 1        4  2.32              1
4     6  Periodo 1        5  4.33              1
..   ..        ...      ...   ...            ...
193  11  Periodo 3        7  5.00              1
194  11  Periodo 3        8  2.26              1
195  11  Periodo 3        9  3.35              1
196  11  Periodo 3       10  1.41              1
197  11  Periodo 3       11  4.44              1

[198 rows x 5 columns]

# Tabla de ponderación

In [ ]:
tabla_ponderacion = pd.DataFrame({"Materias" : [1,2,3,4,5,6,7,8,9,10,11],
"Ing. de Sistemas Afines"   :[0.2,0.05,0.1,0.05,0.15,0,0.25,0.05,0,0.05,0.1],
"Ing. Industria"            :[0.2,0.1,0.15,0.1,0.1,0,0.15,0.05,0,0.05,0.1],
"Medicina"                  :[0.1,0.15,0.25,0.05,0.05,0.05,0.05,0.05,0,0.1,0.15],
"Enfermería"                :[0.1,0.1,0.25,0.05,0.05,0.05,0.05,0.1,0,0.1,0.15],
"Derecho"                   :[0.05,0.25,0.05,0.25,0,0,0.05,0.05,0.05,0.15,0.1],
"Adm Empresas "             :[0.15,0.1,0.05,0.15,0.1,0,0.1,0.05,0,0.1,0.2] ,
"Psicología"                :[0.1,0.15,0.1,0.2,0.1,0,0.05,0.05,0.05,0.15,0.05] ,
"Contaduría"                :[0.15,0.1,0.05,0.15,0.1,0,0.1,0.05,0,0.05,0.25] ,
"Ing Ambiental"             :[0.15,0.1,0.25,0.1,0.1,0,0.1,0.05,0,0.05,0.1] ,
"Ing Electrónica"           :[0.25,0.05,0.2,0.05,0.1,0,0.2,0.05,0,0.05,0.05] ,
"Marketing Digital"         :[0.1,0.1,0.05,0.15,0.15,0,0.2,0.05,0,0.05,0.15] ,
"Ing Mecánica "             :[0.25,0.05,0.2,0.05,0.1,0,0.15,0.05,0,0.05,0.1] ,
"Arquitectura"              :[0.15,0.1,0.1,0.05,0.1,0,0.15,0.2,0,0.05,0.1] ,
"Educación(STEM)"           :[0.2,0.1,0.2,0.1,0.1,0,0.15,0.05,0,0.05,0.05] ,
"Economía"                  :[0.15,0.1,0.05,0.2,0.1,0,0.05,0.05,0,0.1,0.2] ,
"Finanzas RelacionesInte"   :[0.1,0.1,0.05,0.25,0.15,0,0.1,0.05,0,0.1,0.1] ,
"Ing Agronómica"            :[0.15,0.1,0.25,0.1,0.1,0,0.1,0.05,0,0.05,0.1] ,
"Biología y Biotecnología " :[0.1,0.1,0.3,0.05,0.1,0,0.1,0.05,0,0.1,0.1] ,
"Diseño Gráfico Industrial ":[0.1,0.1,0.05,0.05,0.1,0, 0.2, 0.25,0,0.05,0.1] ,
"Turismo y Hospitalidad "   :[0.05,0.15,0.05,0.2,0.15,0,0.1,0.1,0,0.1,0.1]})

In [ ]:
# Número de filas y columnas de la tabla de ponderación
print(f"Número de filas: {tabla_ponderacion.shape[0]}")
print(f"Número de columnas: {tabla_ponderacion.shape[1]}")

# Nombres de las columnas de la tabla de ponderación
print(f"Nombres de las columnas: {list(tabla_ponderacion.columns)}")

# Tipos de datos de cada columna de la tabla de ponderación
print(f"Tipos de datos de las columnas: {tabla_ponderacion.dtypes}")




Número de filas: 11
Número de columnas: 21
Nombres de las columnas: ['Materias', 'Ing. de Sistemas Afines', 'Ing. Industria', 'Medicina', 'Enfermería', 'Derecho', 'Adm Empresas ', 'Psicología', 'Contaduría', 'Ing Ambiental', 'Ing Electrónica', 'Marketing Digital', 'Ing Mecánica ', 'Arquitectura', 'Educación(STEM)', 'Economía', 'Finanzas RelacionesInte', 'Ing Agronómica', 'Biología y Biotecnología ', 'Diseño Gráfico Industrial ', 'Turismo y Hospitalidad ']
Tipos de datos de las columnas: Materias                        int64
Ing. de Sistemas Afines       float64
Ing. Industria                float64
Medicina                      float64
Enfermería                    float64
Derecho                       float64
Adm Empresas                  float64
Psicología                    float64
Contaduría                    float64
Ing Ambiental                 float64
Ing Electrónica               float64
Marketing Digital             float64
Ing Mecánica                  float64
Arquitectura  

In [ ]:
import pandas as pd
tabla_ponderacion_melted = tabla_ponderacion.melt(id_vars=['Materias'], var_name='Carrera', value_name='Ponderacion')

resultados = []  # Lista para guardar los resultados de cada DataFrame.

for df_estudiante in dataframes_por_estudiante:
    # Crea una copia segura del DataFrame para evitar SettingWithCopyWarning.
    df_estudiante_safe = df_estudiante.copy()

    # Asegura que las materias en df_estudiante están en el formato correcto para fusionar.
    df_estudiante_safe['materia'] = df_estudiante_safe['materia'].astype(int)

    # Fusiona df_estudiante con las ponderaciones.
    df_con_ponderaciones = pd.merge(df_estudiante_safe, tabla_ponderacion_melted, how='left', left_on='materia', right_on='Materias')

    # Aplica las ponderaciones a cada nota.
    df_con_ponderaciones['nota_ponderada'] = df_con_ponderaciones['nota'] * df_con_ponderaciones['Ponderacion']

    # No agrupes todavía por 'año' y 'periodo' si deseas mantener cada registro de nota individualmente.
    resultados.append(df_con_ponderaciones)



In [ ]:
def calcular_ponderacion_total(df):
  """
  Calcula la ponderación total para cada fila del DataFrame.

  Args:
      df: DataFrame con las notas ponderadas.

  Returns:
      DataFrame con la ponderación total para cada fila.
  """

  df['ponderacion_total'] = df.groupby(['id_estudiante', 'año', 'periodo', 'Carrera'])['nota_ponderada'].transform('sum')
  return df

def ordenar_por_puntaje(df):
  """
  Ordena el DataFrame por puntaje mayor a menor.

  Args:
      df: DataFrame con las notas ponderadas.

  Returns:
      DataFrame ordenado por puntaje mayor a menor.
  """

  df = df.sort_values(by='ponderacion_total', ascending=False)
  return df

# Calcular la ponderación total y ordenar por puntaje para cada DataFrame en la lista.
for i in range(len(resultados)):
  resultados[i] = calcular_ponderacion_total(resultados[i])
  resultados[i] = ordenar_por_puntaje(resultados[i])

# Ahora, cada DataFrame en la lista 'resultados' está organizado por puntaje mayor a menor.


In [ ]:
resultados[2]

año    periodo  materia  nota  id_estudiante  Materias  \
2139   9  Periodo 1        8  4.78              3         8   
2079   9  Periodo 1        5  3.68              3         5   
2059   9  Periodo 1        4  4.82              3         4   
2039   9  Periodo 1        3  3.68              3         3   
2119   9  Periodo 1        7  3.65              3         7   
...   ..        ...      ...   ...            ...       ...   
1084   7  Periodo 2       11  2.70              3        11   
1044   7  Periodo 2        9  1.87              3         9   
904    7  Periodo 2        2  1.42              3         2   
924    7  Periodo 2        3  3.25              3         3   
984    7  Periodo 2        6  1.19              3         6   

                      Carrera  Ponderacion  nota_ponderada  ponderacion_total  
2139  Turismo y Hospitalidad          0.10          0.4780             4.0025  
2079  Turismo y Hospitalidad          0.15          0.5520             4.0025  
2059  Turismo y Hospitalidad          0.20          0.9640             4.0025  
2039  Turismo y Hospitalidad          0.05          0.1840             4.0025  
2119  Turismo y Hospitalidad          0.10          0.3650             4.0025  
...                       ...          ...             ...                ...  
1084                  Derecho         0.10          0.2700             1.8305  
1044                  Derecho         0.05          0.0935             1.8305  
904                   Derecho         0.25          0.3550             1.8305  
924                   Derecho         0.05          0.1625             1.8305  
984                   Derecho         0.00          0.0000             1.8305  

[3960 rows x 10 columns]

In [ ]:
# Create a dictionary to map the career names to their corresponding numerical values.
carrera_dict = {
   'Ing. de Sistemas Afines': 1,
    'Ing. Industria': 2,
    'Medicina': 3,
    'Enfermería': 4,
    'Derecho': 5,
    'Adm Empresas ': 6,
    'Psicología': 7,
    'Contaduría': 8,
    'Ing Ambiental': 9,
    'Ing Electrónica': 10,
    'Marketing Digital': 11,
    'Ing Mecánica ': 12,
    'Arquitectura': 13,
    'Educación(STEM)': 14,
    'Economía': 15,
    'Finanzas RelacionesInte': 16,
    'Ing Agronómica': 17,
    'Biología y Biotecnología ': 18,
    'Diseño Gráfico Industrial ': 19,
    'Turismo y Hospitalidad ': 20
}

# Loop through all dataframes in the list 'resultados'.
for df in resultados:
    # Replace the career names with their corresponding numerical values.
    df['Carrera'] = df['Carrera'].replace(carrera_dict)




In [ ]:
resultados[0]

año    periodo  materia  nota  id_estudiante  Materias  Carrera  \
3049  10  Periodo 2       10  4.53              1        10       10   
2969  10  Periodo 2        6  3.63              1         6       10   
2869  10  Periodo 2        1  4.67              1         1       10   
2989  10  Periodo 2        7  3.85              1         7       10   
3069  10  Periodo 2       11  3.61              1        11       10   
...   ..        ...      ...   ...            ...       ...      ...   
1996   9  Periodo 1        1  1.23              1         1       17   
2028   9  Periodo 1        3  1.22              1         3        9   
2096   9  Periodo 1        6  4.43              1         6       17   
2036   9  Periodo 1        3  1.22              1         3       17   
2168   9  Periodo 1       10  3.77              1        10        9   

      Ponderacion  nota_ponderada  ponderacion_total  
3049         0.05          0.2265             3.7825  
2969         0.00          0.0000             3.7825  
2869         0.25          1.1675             3.7825  
2989         0.20          0.7700             3.7825  
3069         0.05          0.1805             3.7825  
...           ...             ...                ...  
1996         0.15          0.1845             2.0565  
2028         0.25          0.3050             2.0565  
2096         0.00          0.0000             2.0565  
2036         0.25          0.3050             2.0565  
2168         0.05          0.1885             2.0565  

[3960 rows x 10 columns]

In [ ]:
def obtener_mejores_puntajes(resultados):

  mejores_puntajes = []

  for df in resultados:
    df_mejores = df[['id_estudiante', 'ponderacion_total', 'Carrera']].head(3)
    df_mejores = df_mejores.drop_duplicates(subset='ponderacion_total', keep='first')
    mejores_puntajes.append(df_mejores.values.tolist())

  return mejores_puntajes

mejores_puntajes = obtener_mejores_puntajes(resultados)


In [ ]:
# prompt: hacer q esta lista resultados  dataframe se vuelva un solo dataframe

import pandas as pd
datos_unificados = pd.concat(resultados, ignore_index=True)


In [ ]:
datos_unificados.head(1)

año    periodo  materia  nota  id_estudiante  Materias  Carrera  \
0  10  Periodo 2       10  4.53              1        10       10   

   Ponderacion  nota_ponderada  ponderacion_total  
0         0.05          0.2265             3.7825

In [ ]:
# prompt: hacer que la columna año sea int

datos_unificados['año'] = datos_unificados['año'].astype(int)


In [ ]:

datos_unificados['periodo'] = datos_unificados['periodo'].replace({'Periodo 1': 1, 'Periodo 2': 2,'Periodo 3': 2}).astype(int)


In [ ]:
datos_unificados.head(3)


año  periodo  materia  nota  id_estudiante  Materias  Carrera  Ponderacion  \
0   10        2       10  4.53              1        10       10         0.05   
1   10        2        6  3.63              1         6       10         0.00   
2   10        2        1  4.67              1         1       10         0.25   

   nota_ponderada  ponderacion_total  
0          0.2265             3.7825  
1          0.0000             3.7825  
2          1.1675             3.7825

In [ ]:
# prompt: agregar una nueva columna con el numero de la Carrera con mayor ponderacion para cada id_estudiantes diferente, y valor maximo de ponderacion total colocar el numero de Carrera correspondiente a los demas valores colcoar 0

import pandas as pd

def agregar_columna_carrera_maxima(df):
  """
  Agrega una nueva columna con el número de la Carrera con mayor ponderación para cada id_estudiantes diferente,
  y valor maximo de ponderacion total colocar el numero de Carrera correspondiente a los demas valores colcoar 0
  """

  # Agrupar por id_estudiante y obtener el número de Carrera con mayor ponderación total.
  df_max_ponderacion = df.groupby('id_estudiante')['ponderacion_total'].idxmax()
  df_max_ponderacion = df.loc[df_max_ponderacion, ['id_estudiante', 'Carrera']]
  df_max_ponderacion.columns = ['id_estudiante', 'Carrera_max_ponderacion']

  # Unir la columna Carrera_max_ponderacion al DataFrame original.
  df = pd.merge(df, df_max_ponderacion, on='id_estudiante', how='left')

  # Rellenar los valores nulos con 0.
  df['Carrera_max_ponderacion'].fillna(0, inplace=True)

  # Convertir la columna Carrera_max_ponderacion a tipo entero.
  df['Carrera_max_ponderacion'] = df['Carrera_max_ponderacion'].astype(int)

  return df

# Aplicar la función al DataFrame.
datos_unificados = agregar_columna_carrera_maxima(datos_unificados)

# Mostrar las primeras filas del DataFrame.
datos_unificados.head(3)


año  periodo  materia  nota  id_estudiante  Materias  Carrera  Ponderacion  \
0   10        2       10  4.53              1        10       10         0.05   
1   10        2        6  3.63              1         6       10         0.00   
2   10        2        1  4.67              1         1       10         0.25   

   nota_ponderada  ponderacion_total  Carrera_max_ponderacion  
0          0.2265             3.7825                       10  
1          0.0000             3.7825                       10  
2          1.1675             3.7825                       10

In [ ]:
datos_unificados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158400 entries, 0 to 158399
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype  
---  ------                   --------------   -----  
 0   año                      158400 non-null  int64  
 1   periodo                  158400 non-null  int64  
 2   materia                  158400 non-null  int64  
 3   nota                     158400 non-null  float64
 4   id_estudiante            158400 non-null  int64  
 5   Materias                 158400 non-null  int64  
 6   Carrera                  158400 non-null  int64  
 7   Ponderacion              158400 non-null  float64
 8   nota_ponderada           158400 non-null  float64
 9   ponderacion_total        158400 non-null  float64
 10  Carrera_max_ponderacion  158400 non-null  int64  
dtypes: float64(4), int64(7)
memory usage: 14.5 MB


In [ ]:
!pip install xgboost


In [ ]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt


In [ ]:
# Cargar datos
# datos_unificados = pd.read_csv('ruta/a/tu/dataset.csv')
# Asumiendo que tienes tu DataFrame listo como `datos_unificados`

# Dividir los datos en características y target
X = datos_unificados.drop('Carrera_max_ponderacion', axis=1)
y = datos_unificados['Carrera_max_ponderacion']

# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
from sklearn.preprocessing import LabelEncoder

# Crear un codificador de etiquetas y ajustarlo a las etiquetas de tu conjunto de datos
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Ahora usa y_encoded para la división de entrenamiento/prueba y para entrenar el modelo
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)


In [ ]:
params = {
    'max_depth': 6,
    'eta': 0.3,
    'objective': 'multi:softmax',
    'num_class': len(np.unique(y_encoded))  # Actualizar aquí con el número correcto de clases únicas
}

dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

model = xgb.train(params, dtrain, num_boost_round=100)

y_pred = model.predict(dtest)

In [ ]:
# Calcular la precisión
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Generar la matriz de confusión
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

# Generar el reporte de clasificación
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 1.00
Confusion Matrix:
 [[2394    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0 1644    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0  795    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0 3940    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0 1628    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0 3158    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0 5519    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0 2365    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0  820    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0 2300    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0  804    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0 5544    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0  769]]
Classification Report:
               precision    recall  f1-score   support

  

In [ ]:
!pip install tensorflow
from sklearn.preprocessing import StandardScaler

# Escalar las características
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Número de características en tus datos
input_shape = X_train_scaled.shape[1]

# Construir el modelo
model = Sequential([
    Dense(64, activation='relu', input_shape=(input_shape,)),
    Dense(64, activation='relu'),
    Dense(len(np.unique(y)), activation='softmax')  # Usar softmax para clasificación multiclase
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                704       
                                                                 
 dense_1 (Dense)             (None, 64)                4160      
                                                                 
 dense_2 (Dense)             (None, 13)                845       
                                                                 
Total params: 5709 (22.30 KB)
Trainable params: 5709 (22.30 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
history = model.fit(X_train_scaled, y_train, epochs=100, validation_split=0.2, batch_size=32)


Epoch 1/100
3168/3168 [==============================] - 17s 4ms/step - loss: 1.8504 - accuracy: 0.3138 - val_loss: 1.4547 - val_accuracy: 0.4518
Epoch 2/100
3168/3168 [==============================] - 13s 4ms/step - loss: 1.1681 - accuracy: 0.5570 - val_loss: 0.9488 - val_accuracy: 0.6125
Epoch 3/100
3168/3168 [==============================] - 10s 3ms/step - loss: 0.8063 - accuracy: 0.6897 - val_loss: 0.7087 - val_accuracy: 0.7604
Epoch 4/100
3168/3168 [==============================] - 10s 3ms/step - loss: 0.5810 - accuracy: 0.7850 - val_loss: 0.4927 - val_accuracy: 0.7891
Epoch 5/100
3168/3168 [==============================] - 11s 3ms/step - loss: 0.4095 - accuracy: 0.8508 - val_loss: 0.3387 - val_accuracy: 0.8830
Epoch 6/100
3168/3168 [==============================] - 11s 3ms/step - loss: 0.2899 - accuracy: 0.9012 - val_loss: 0.2863 - val_accuracy: 0.9163
Epoch 7/100
3168/3168 [==============================] - 12s 4ms/step - loss: 0.2139 - accuracy: 0.9300 - val_loss: 0.1904 -

In [ ]:
test_loss, test_acc = model.evaluate(X_test_scaled, y_test)
print('\nTest accuracy:', test_acc)

990/990 [==============================] - 2s 2ms/step - loss: 9.1861e-07 - accuracy: 1.0000

Test accuracy: 1.0
